### ISSUE TITLE
Scrollbars are showing up

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#8] opened 2017-05-28 06:32 UTC
Presumably the padding is adding some additional pixels and making vertical and horizontal scroll bars show up in the browser window.

**Comment by lpberg** [comment] 2017-06-13 02:02
for which view?

**Comment by carlsonp** [comment] 2017-06-14 03:23
Cardsort

**Comment by lpberg** [comment] 2017-06-20 23:22
Is this still a thing?

**Comment by lpberg** [comment] 2017-07-05 13:44
Is this still happening? I think I fixed this.

**Comment by lpberg** [comment] 2017-07-19 03:12
closing as I can't reproduce it

**Closed by lpberg** 2017-07-19 03:12 UTC
Labels: bug
